project:
  type: website


website:
  navbar:
    background: "#f5ddce"
    title: "Inicio"          # ← click aquí regresa al inicio
    href: "index.html"      # ← esto lo hace link
  sidebar:
    style: "docked"        # o "floating"
    background: "#fdf4f0"  # color opcional
    contents:
      - section: "**Tareas**"
        contents:
          - text: "1. Set up"
            href: tareas/tarea_01_q.html
          - text: "2. Conexión ssh-github"
            href: tareas/tarea_02.html
      - section: "**Documentos**"
        contents:
          - text: "Temario detallado"
            href: docs/d00_temario.html
          - text: "CSVKIT"
            href: docs/d01_csvkit.html
          - text: "Instalación Python"
            href: docs/d03_instalacion_python.html


html:
  theme: minty
  toc: false

format:
  revealjs:
    theme: white
    highlight-style: ayu
    code-block-border-left: "#ecbb9a"
    code-overflow: wrap
    footer: "[← Regresar al inicio](../index.html)"  # ← esto


lang: es-MX

execute:
  echo: false
  warning: false
  freeze: auto
  cache: true

