---
title: "Introducción a la programación para políticas públicas"
subtitle: "Materiales del clase"

format:
  html:
    other-links:
      - text: Repo del curso
        href: https://github.com/LDataLab/intro-programacion-pp
        icon: github

author:
  - name: Elena Villalobos Nolasco
    orcid: 0009-0005-6389-291X
    email: villalobos_elena@tec.mx
    affiliations: Escuela de Gobierno y Transformación Pública

bibliography: references.bib
---

## Materiales

::: {.callout-tip collapse="false"}
### 01: Introducción

- Introducción a programación para ciencia de datos en políticas públicas
    - [Material 01](materiales/m01_intro.html) 

:::

::: {.callout-tip collapse="false"}
### 02: Bash, CLI e infraestructura

- Introduccción a Bash, CLI y ssh
    - [Material 02](materiales/m02_intro_bash.html) 

- Análisis de datos en cli
    - [Material 03](materiales/m03_data_cli.html) 

:::

::: {.callout-tip collapse="false"}
### 03. Git/GitHub

- Control de versiones básico para trabajo individual y colaborativo
    - [Material 04](materiales/m04_git_github.html) 

- Control de versiones avanzado: colaboración y resolución de conflictos
    - [Material 05](materiales/m05_git_avanzado.html) 


:::

::: {.callout-caution collapse="false"}
### 04. Ambientes virtuales Python

- Estructura para un buen funcionamiento de Python
    - [Material 06](materiales/m06_python.html) 

:::



## Calendario

<details>
<summary><strong>Ver calendario del curso</strong></summary>

| Clase | Tema                                      | Observaciones | Fecha            |
|------:|-------------------------------------------|---------------|------------------|
| 01    | Introducción                              | T1            | [2026-09-17 Thu] |
| 02    | Bash y CLI; Infraestructura               | T2            | [2026-09-24 Thu] |
| 03    | Git/Github                                | T3            | [2026-10-01 Thu] |
| 04    | Ambientes virtuales Python                |               | [2026-10-08 Thu] |
| 05    | Configuración Python                      | T4            | [2026-10-15 Thu] |
| 06    | Variables de entorno y credenciales       |               | [2026-10-22 Thu] |
| 07    | Datos, SQL y bases de datos               | Midterm       | [2026-10-29 Thu] |
| 08    | Docker y ambientes reproducibles          |               | [2026-11-05 Thu] |
| 09    | APIS y servicios externos                 | T5            | [2026-11-12 Thu] |
| 10    | Automatización y verificación automática  | T6*           | [2026-11-19 Thu] |
| 11    | Agentes de programación                   |               | [2026-11-26 Thu] |
| 12    | Evaluación                                | Final         | [2026-12-03 Thu] |

- **T#**: Tarea y número de tarea.
- **Midterm**: Evaluación intermedia.
- **Final**: Evaluación final.

</details>


