---
title: "Tarea 2: Exploración de datos"
format:
  html:
    toc: true
    toc-depth: 2
    theme: cosmo
    highlight-style: github
date: today
---

# Llaves ssh

Secure Shell Protocol (SSH) es un protocolo de red para autenticación segura entre sistemas. Se utiliza para conectarnos con servidores remotos desde nuestra computadora. SSH, utiliza una combinación criptográfica entre llaves para autenticar y cifrar los datos que se transmiten entre el cliente y el servidor, las llaves son:

1. **Clave privada (private key)**: Esta se mantiene en tu computadora local y NUNCA DEBES COMPARTIRLA. 
2. **Clave pública (public key, .pub)**: Esta es la que tienes que compartir con los servidores con los que te quieres conectar, _Ojo: esta es la que me compartirás en el formulario_. 

El proceso de autenticación funciona de la siguiente manera: cuando intentas conectarte a un servidor, éste usa tu clave pública para crear un desafío que solo puede ser resuelto con tu clave privada. Si el servidor confirma que las claves coinciden, te permite el acceso.

Para poder comunicarte con la infraestructura de la EGobiernoyTP requieres generar unas llaves con SSH en tu computadora. Dependiendo del sistema operativo con el que cuentes se indican los pasos a seguir para generar este par de llaves privada y pública.

`ssh-keygen -t ed25519 -C "<comentario que identifique llave"`

## Manual detallado de instalación

### Windows

Generar llaves privadas y públicas con windows. 

Pre requisitos: 
- Windows 10-11.
- Cuenta de usuario con Acceso a la terminal.
- Acceso a un *web browser*.

#### Pasos  


##### 1. Verifica si tienes instalado OpenSSH:  


- Ve a `Settings`y luego selecciona `Apps & Features`.
- Dentro de `Apps & Features` seleccionar `Optional Features`.
- Buscar si en la lista aparece `OpenSSH Client`, si aparece, continua con el paso 2, si no aparece continua con: 
  - Si no está enlistado, selecciona el signo de `+` que está junto a `Add feature`.
  - Busca en esa lista la opción `OpenSSH Client` y selecciónala.
  - Selecciona la opción `Install`.

##### 2. Abrir el command prompt 


- Presiona la tecla de windows en tu teclado.
- Escribe `cmd`. Te aparecerá la opción `Command prompt`.
- Selecciona abrir `Command prompt`como administrador. 
- Si aparece una ventana que pregunta si quieres permitir que esta aplicación haga cambios a tu máquina, selecciona `yes`.

##### 3. Utiliza OpenSSH para generar tus llaves privada y pública con ssh. 


- En el `Command Prompt` ingresa el siguiente comando `ssh-keygen`. Por default ssh genera tu par de llaves con el nombre `id_rsa`.
  - Si nunca has creado antes un par de llaves ssh entonces deja este nombre por default. 
  - Si ya tienes un par de llaves creadas antes entonces cambia el nombre del archivo.
  - Tus llaves quedarán guardadas en el directorio `C:\Users\tu_usuario/ .ssh/` (nota que el directorio ssh tiene
un punto antes `.ssh`).
- Presiona enter para que se generen las llaves.
- Se te preguntará por un `passphrase`, este será el password asociado a tu par de llaves pública y privada. Asigna un password que vayas a recordar, nota que la estarás ocupando continuamente en la infraestructura.
- Una vez asociado el `passphrase` te mostrará una especie de imagen hecha con caracteres. Eso significa que tu par de llaves ssh han sido generadas.

##### 4. Abre tu explorador de archivos 

- Navega hasta el directorio donde se generaron tus llaves: `C:\Users\tu_usuario/ .ssh/`.
- Debes ver 2 archivos, uno llamado id_rsa y otro con el mismo nombre pero con terminación `.pub`. 
- El archivo que no tiene extensión es tu llave privada, **no la debes compartir con nadie, nunca**. Si algún día compartes este archivo, tus llaves ya no sirven, tienes que generar otro par.
- El archivo que termina con la extensión `.pub` es tu llave pública, este archivo lo puedes compartir con quien tu quieras y como tu quieras, compartirlo no compromete tu seguridad.

##### 5. Compartir tu llave pública 


- El archivo `.pub` es el que se agregará a la infraestructura para que puedas entrar. Para esto, abre el archivo .pub (con cualquier editor de texto), copia en el portapapeles el contenido y pégalo en el formulario que se te envió junto con este manual.  

##### 6. Espera indicaciones de regreso por parte del administrador de la infraestructura.  

- Se te enviará un archivo que tendrá tu usuario y credenciales para ingresar a la infraestructura.

*Referencia: [How to generate ssh key in windows 10](https://phoenixnap.com/kb/generate-ssh-key-windows-10).*

### MacOS

Generar llaves privadas y públicas con MacOS. 

#### Pasos 

##### 1. Encontrar `ssh-keygen` 

- En `Finder` en `Applications` selecciona la opción `Utilities`.
- En la lista que se muestre selecciona `Terminal` y abre la `Terminal`.

##### 2. Generar llave 

- En la `Terminal` escribe la siguiente instrucción `ssh-keygen -t rsa`. Esto iniciará la generación de tu par de llaves pública y privada. Por default `ssh` genera tu par de llaves con el nombre `id_rsa`.
  - Si no has creado antes un par de llaves ssh entonces deja este nombre por default.
  - Si ya tienes un par de llaves creadas antes entonces cambia el nombre del archivo.
- Tus llaves quedarán guardadas en el directorio `/Users/tu_usuario/.ssh/` (nota que el directorio ssh tiene un punto antes `.ssh`). Presiona enter para que se generen las llaves.
- Se te preguntará por un `passphrase`, este será el password asociado a tu par de llaves pública y privada, asigna una que vayas a recordar, pues lo estarás ocupando continuamente en la infraestructura.
- Una vez asociado el passphrase te mostrará una especie de imagen hecha con caracteres. Eso significa que tu par de llaves ssh han sido generadas.

##### 3. Abre tu explorador de archivos 

- Navega hasta el directorio donde se generaron tus llaves:
/Users/tu_usuario/.ssh/
- Debes ver 2 archivos, uno llamado id_rsa y otro con el mismo nombre pero con terminación `.pub`. 
- El archivo que no tiene extensión es tu llave privada, **no la debes compartir con nadie, nunca**. Si algún día compartes este archivo, tus llaves ya no sirven, tienes que generar otro par.
- El archivo que termina con la extensión `.pub` es tu llave pública, este archivo lo puedes compartir con quien tu quieras y como tu quieras, compartirlo no compromete tu seguridad.

##### 4. Compartir tu llave pública 

- El archivo `.pub` es el que se agregará a la infraestructura para que puedas entrar. Para esto, abre el archivo .pub (con cualquier editor de texto), copia en el portapapeles el contenido y pégalo en el formulario que se te envió junto con este manual.  

##### 5. Espera indicaciones de regreso por parte del administrador de la infraestructura.  

- Se te enviará un archivo que tendrá tu usuario y credenciales para ingresar a la infraestructura.

*Referencias: [Manually generating your SSH key in macOS](https://docs.tritondatacenter.com/public-cloud/getting-started/ssh-keys/generating-an-ssh-key-manually/manually-generating-your-ssh-key-in-mac-os-x)*



### Linux

##### 1. Generar llaves 

- Abre una terminal.
- Escribe la instrucción `ssh-keygen -t rsa`. Esto iniciará la generación de tu par de llaves pública y privada. Por default ssh genera tu par de llaves con el nombre id_rsa.
    - Si no has creado antes un par de llaves ssh entonces deja este nombre por default.
    - Si ya tienes un par de llaves creadas antes entonces cambia el nombre del archivo.
- Tus llaves quedarán guardadas en el directorio `/Users/tu_usuario/.ssh/`  (nota que el directorio ssh tiene un punto antes `.ssh`). Presiona enter para que se generen las llaves.
- Se te preguntará por un passphrase, este será el password asociado a tu par de llaves pública y privada. Asigna un password que vayas a recordar, lo estarás ocupando continuamente en la infraestructura. Una vez asociado el passphrase te mostrará una especie de imagen hecha con caracteres. Eso significa que tu par de llaves ssh han sido generadas.

##### 2. Abre tu explorador de archivos 

- Navega hasta el directorio donde se generaron tus llaves: `/Users/tu_usuario/.ssh/`. 
- Debes ver 2 archivos, uno llamado id_rsa y otro con el mismo nombre pero con terminación .pub. El archivo que no tiene extensión es tu llave privada, **no la debes compartir con nadie, nunca**. Si algún día compartes este archivo, tus llaves ya no sirven, tienes que generar otro par. 
- El archivo que termina con la extensión .pub es tu llave pública, este archivo lo puedes compartir con quien tu quieras y como tu quieras, compartirlo no compromete tu seguridad.

##### 3. Compartir tu llave pública 

- El archivo `.pub` es el que se agregará a la infraestructura para que puedas entrar. Para esto, abre el archivo .pub (con cualquier editor de texto), copia en el portapapeles el contenido y pégalo en el formulario que se te envió junto con este manual.    

