---
title: "Tarea 2: Exploración de datos"
format:
  html:
    toc: true
    toc-depth: 2
    theme: cosmo
    highlight-style: github
date: today
---

# Bash

GNU Bash o simplemente Bash (Bourne-again shell) es una **interfaz de línea de
comandos** o intérprete de órdenes que generalmente se ejecuta en una ventana de 
texto donde el usuario escribe órdenes en modo texto. Bash también puede leer y 
ejecutar órdenes desde un archivo, llamado `script`. 

Éste intérprete de comandos es parte de los sistemas operativos basados en **Unix**, como Linux y macOS.
Es la interfaz que nos permite **interactuar directamente con el sistema operativo** 
a través de la línea de comandos, en lugar de una interfaz gráfica (GUI). 

#### Sistemas basados en GUI: 

- Windows usa principalmente interfaces gráficas (GUI), aunque tiene su línea de 
comandos (Command Prompt) y **PowerShell**.
- Linux/macOS: Estos sistemas están **diseñados** alrededor de una filosofía donde 
el acceso a través de **la línea de comandos es central**. Las interfaces gráficas
son opcionales, mientras que el manejo mediante la terminal es más directo y 
eficiente para muchas tareas.

Interactuar desde la línea de comandos es algo que todo desarrollar o científico de 
datos debería aprender e implementar en sus tareas diarias, pues nos permite tener 
un mayor control nuestros sistemas y ser más productivos. 

#### Archivos y directorios

La computadora guarda la información de una manera ordenada. El sistema encargado de
esto es el **file system**, el cual es básicamente un árbol de información que 
guarda los datos en una abstracción que llamamos archivos y ordena **los archivos en
carpetas y directorios**, los cuales pueden contener otros directorios.

**TODO** en los sistemas operativos Unix (Linux, MacOs), es un **archivo**. Muchos
de los comandos de CLI o shell tienen que ver con la manipulación del file system. 


## Comandos principales

- Encuentra la Terminal en Mac y PowerShell en Windows, y coloca 

```{.sh}
echo "Hola Mundo"
```

- ¿Quién soy?

```{.sh}
whoami
```

- ¿Cuál es tu directorio actual? Ver en qué directorio nos encontramos situados (Print working directory)

```{.sh}
pwd
```

- Cambia de directorio

```{.sh}
cd <directorio>
```


- Regresa a donde estabas antes

```{.sh}
cd ..
```

- Día de hoy 

```{.sh}
date
```

- Lista todos los archivos en el directorio actual pero no los ocultos

```{.sh}
ls
```

- Move or rename directory

```{.sh}
mv
```

- Copiar archivos

```{.sh}
cp
```


- Create directory

```{.sh}
mkdir
```




#### SSH

Recordemos que la sesión pasada vimos SSH, el protocolo de red para autenticación segura entre sistemas. Se utiliza para conectarnos con servidores remotos desde nuestra computadora. 

1. **Clave privada (private key)**: Esta se mantiene en tu computadora local y NUNCA DEBES COMPARTIRLA. 
2. **Clave pública (public key, .pub)**: Esta es la que tienes que compartir con los servidores con los que te quieres conectar.

Existen dos tipos de algoritmos critográficos:

1. RSA: Rivest-Shamir-Adleman (`id_rsa`/`id_rsa.pub`)
2. Ed25519: Edwards-curve Digital Signature Algorithm (`id_ed25519`/`id_ed25519.pub`)

La manera en la que se generan de manera general es: 

```
ssh-keygen -t ed25519 -C "tu_correo@dominio.com"
```

o

```
ssh-keygen -t rsa -b 4096 -C "tu_correo@dominio.com"
```

El algoritimo ed25519 es más moderno y recomendado. Cada vez que quieras conectarte a un servidor, puedes crear una nueva llave o utilizar la que ya tienes, **OJO: Solo comparte tu llave pública en servidores seguros.**

### Conectarte a bastion

SSH hace la conexión segura esto es solo sintaxis: 

```
ssh -i <la llave privada para autenticarse> <tu_usuario>@<host o IP del servidor al que te conectas>
```

- Host: Nombre con el que identificamos una computadora en la red, usualmente son nombres fáciles de recodar. 
- IP (Internet Protocol address): es como la dirección única de una computadora en la red
	- La IP sería como la coordenada exacta, y el host el apodo que internamente apunta a una IP. 
- Keep-alive (el cliente enviará un mensaje cada 60 segundos para que no se cierre la conexión por inactividad)

Si tu llave es ed25519:

```
ssh -i .ssh/id_ed25519 <tu_usuario>@bastion.egobiernoytp.io -o ServerAliveInterval=60

```

Si es rsa:

```
ssh -i ~/.ssh/id_rsa <tu_usuario>@bastion.egobiernoytp.io -o ServerAliveInterval=60
```


### Conexión de bastión a Gitlab utilizando SSH

Cuando trabajamos con repositorios en GitHub/GitLab/Codeberg/etc., podemos conectarnos de dos formas:

1. HTTPS: funciona con usuario y contraseña o token cada vez que interactúas (pull/push).
2. SSH: funciona con un par de llaves (pública y privada) y solo tienes que configurarla al inicio.

Nosotros como ya sabemos utilizar ssh, haremos la conexión de bastión a Gitlab de la siguiente manera: 

- Copiar tu llave pública en Gitlab:
	- Da click en tu foto de perfil, luego: `Preferences → SSH Keys → Add new key`
	- Pega la llave en donde dice key y quita la Expiration date. 

Podrás clonar fácilmente el repositorio.

```{.sh}
git clone <URL>
```


### Más comandos útiles

- Iniciar el editor nano 

```{.sh}
nano <nombre_documento>
```

- Ver el contenido del archivo

```{.sh}
cat <nombre_documento>
```

- Borrar archivo

```{.sh}
rm <nombre_documento>
```

- Borrar directorio

```{.sh}
rmdir <nombre_documento>
```

## Navegación en la Terminal

- La tecla tab completa la palabra por ti.

- Inicio de la línea

```{.sh}
ctrl + a
```

- Fin de la línea
```{.sh}
ctrl + e
```

- Busca hacia atrás
```{.sh}
ctrl + r
```

- Elimina el resto de la línea
```{.sh}
ctrl + k
```

- Manda a background el programa que estás ejecutando
```{.sh}
ctrl + z
```

- Intenta cancelar
```{.sh}
ctrl + c
```

- Limpia la pantalla
```{.sh}
ctrl + l
```

- ¿Qué hace?

```{.sh}
history
```
